name: torrenttools
on:
  workflow_dispatch:
    inputs:
      name:
        description: Name of the torrent file
        required: true
        default: The.Nun.2018.1080p.WEBRip.x264
      comment:
        description: Comment
        required: true
        default: The.Nun.2018.1080p.WEBRip.x264 en-US by endweb-xyz
      url:
        description: URL of the file
        required: true
        default: 'https://drive.endweb.xyz/0:/The%20Nun%20(2018)%20[WEBRip]%20[1080p]%20[YTS.AM]/The.Nun.2018.1080p.WEBRip.x264-[YTS.AM].mp4'
      file_name:
        description: File name of the file in the torrent
        required: true
        default: The.Nun.2018.1080p.WEBRip.x264-[YTS.AM].mp4
      piece_size:
        description: Piece Size. Use auto for automatic calculation, or use the recommended piece size on the README.md file
        required: true
        default: auto
      protocol_version:
        description: BitTorrent Protocol version 1, 2, or hybrid
        required: true
        default: 1
        type: choice
        options: [1, 2, hybrid]
      maximize_disk_space:
        description: Maximize disk space. Check if getting out of disk space error
        type: boolean
        
jobs:
  create_torrent:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize disk space
        if: inputs.maximize_disk_space
        uses: easimon/maximize-build-space@v6
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          
      - name: Install torrenttools
        run: |
          sudo add-apt-repository -y ppa:fbdtemme/torrenttools
          sudo apt-get -qq -y install torrenttools
          
      - name: Download file
        run: aria2c -x 16 -o "${{ inputs.file_name }}" "${{ inputs.url }}"
        
      - name: Create torrent using torrenttools
        run: torrenttools create -v "${{ inputs.protocol_version }}" -o "${{ inputs.name }}.torrent" -w "${{ inputs.url }}" -c "${{ inputs.comment }}" -l "${{ inputs.piece_size }}" -s "torrent-webseed-creator" "${{ inputs.file_name }}"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.name }}
          path: ${{ inputs.name }}.torrent
